controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      front_left_wheel_command_joint_name: velocity_left_1_joint
      rear_left_wheel_command_joint_name: velocity_left_2_joint
      front_right_wheel_command_joint_name: velocity_right_1_joint
      rear_right_wheel_command_joint_name: velocity_right_2_joint
      front_left_wheel_state_joint_name: velocity_left_1_joint
      rear_left_wheel_state_joint_name: velocity_left_2_joint
      front_right_wheel_state_joint_name: velocity_right_1_joint
      rear_right_wheel_state_joint_name: velocity_right_2_joint
      kinematics:
        base_frame_offset:
          x: 0.0
          y: 0.0
          theta: 0.0
        wheels_radius: 0.0485
        sum_of_robot_center_projection_on_X_Y_axis: 0.185
      publish_rate: 50.0
      reference_timeout: 10.0
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true