controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Declare the controllers that you want to run
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    type: mecanum_drive_controller/MecanumDriveController
    front_left_wheel_command_joint_name: "velocity_left_1_joint"
    front_right_wheel_command_joint_name: "velocity_right_1_joint"
    rear_left_wheel_command_joint_name: "velocity_left_2_joint"
    rear_right_wheel_command_joint_name: "velocity_right_2_joint"
    front_left_wheel_state_joint_name: "velocity_left_1_joint"
    front_right_wheel_state_joint_name: "velocity_right_1_joint"
    rear_left_wheel_state_joint_name: "velocity_left_2_joint"
    rear_right_wheel_state_joint_name: "velocity_right_2_joint"
    
    # Command interface configuration
    cmd_vel_timeout: 0.5  # seconds
    reference_timeout: 10.0  # seconds
    publish_rate: 50.0   # Hz
    
    # Time synchronization
    use_stamped_vel: true
    velocity_rolling_window_size: 10
    
    # Odometry settings - try different parameter names
    position_feedback: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    enable_odom_tf: true
    publish_odom_tf: true  # Alternative parameter name
    
    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.0485
      sum_of_robot_center_projection_on_X_Y_axis: 0.185
      
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 6.0, 12.0, 18.0, 24.0, 30.0]
    
    # Additional parameters to fix transform timing
    tf_frame_prefix_enable: false
    tf_frame_prefix: ""
