controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      front_left_wheel_command_joint_name: velocity_left_1_joint
      rear_left_wheel_command_joint_name: velocity_left_2_joint
      front_right_wheel_command_joint_name: velocity_right_1_joint
      rear_right_wheel_command_joint_name: velocity_right_2_joint
      wheel_radius: 0.0485
      wheel_separation_width: 0.2676
      wheel_separation_length: 0.12
      publish_rate: 50.0
      command_timeout: 0.5