controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      front_left_wheel_command_joint_name: velocity_left_1_joint
      rear_left_wheel_command_joint_name: velocity_left_2_joint
      front_right_wheel_command_joint_name: velocity_right_1_joint
      rear_right_wheel_command_joint_name: velocity_right_2_joint
      wheel_radius: 0.0485
      wheel_separation_width: 0.12
      wheel_separation_length: 0.263
      publish_rate: 50.0
      command_timeout: 10.0
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
      cmd_vel_timeout: 0.5
      publish_wheel_data: true
      publish_odom_tf: true