# controller_manager:
ros__parameters:
  update_rate: 100  # main control loop [Hz]

  # Joint state broadcaster (needed so the controller can read wheel velocities)
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

  # Mecanum drive controller: reads encoder state, computes odom & TF
  mecanum_drive_controller:
    type: mecanum_drive_controller/MecanumDriveController
    # names of your four wheel joints, in the same order as on the robot
    front_left_wheel_command_joint_name: velocity_left_1_joint
    rear_left_wheel_command_joint_name: velocity_left_2_joint
    front_right_wheel_command_joint_name: velocity_right_1_joint
    rear_right_wheel_command_joint_name: velocity_right_2_joint

    # robot geometry (meters)
    wheel_radius:             0.0485
    wheel_separation_width:   0.2676
    wheel_separation_length:  0.12

    publish_rate: 50.0       # odom publish & TF rate [Hz]
    command_timeout: 0.5     # if no cmd, zero velocities

    # (optional) tune your pose & twist covariances:
    # pose_covariance:  [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                    0.0, 0.05, 0.0, 0.0, 0.0, 0.0,
    #                    0.0,    0.0, 1e6,0.0, 0.0, 0.0,
    #                    0.0,    0.0, 0.0, 1e6,0.0, 0.0,
    #                    0.0,    0.0, 0.0, 0.0, 1e6,0.0,
    #                    0.0,    0.0, 0.0, 0.0, 0.0, 0.05]
    # twist_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                    0.0, 0.05, 0.0, 0.0, 0.0, 0.0,
    #                    0.0,    0.0, 1e6,0.0, 0.0, 0.0,
    #                    0.0,    0.0, 0.0, 1e6,0.0, 0.0,
    #                    0.0,    0.0, 0.0, 0.0, 1e6,0.0,
    #                    0.0,    0.0, 0.0, 0.0, 0.0, 0.05]
