# QoS overrides for sensor data to ensure compatibility
publishers:
  /kinect/points:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/image_raw:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/depth/image_raw:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/camera_info:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/depth/camera_info:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5

subscribers:
  /kinect/points:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/image_raw:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
  /kinect/depth/image_raw:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 5
