# controller_manager:
#   ros__parameters:
#     update_rate: 100
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#     mecanum_drive_controller:
#       type: mecanum_drive_controller/MecanumDriveController
#       front_left_wheel_command_joint_name: velocity_left_1_joint
#       rear_left_wheel_command_joint_name: velocity_left_2_joint
#       front_right_wheel_command_joint_name: velocity_right_1_joint
#       rear_right_wheel_command_joint_name: velocity_right_2_joint
#       wheel_radius: 0.0485
#       wheel_separation_width: 0.2676
#       wheel_separation_length: 0.12
#       publish_rate: 50.0
#       command_timeout: 0.5

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    update_rate_offset: 0.05

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
      front_left_wheel_command_joint_name: velocity_left_1_joint
      front_right_wheel_command_joint_name: velocity_right_1_joint
      rear_right_wheel_command_joint_name: velocity_right_2_joint
      rear_left_wheel_command_joint_name: velocity_left_2_joint
    diagnostics:
      threshold:
        controller_manager:
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
        controllers:
          execution_time:
            mean_error:
              error: 2000.0
              warn: 1000.0
            standard_deviation:
              error: 200.0
              warn: 100.0
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
    

mecanum_drive_controller:
  ros__parameters:
    is_async: true
    update_rate: 20  # Hz
    reference_timeout: 5.0

    # custom parameters for testing
    simulated_delay_min: 45.0
    simulated_delay_max: 48.0
    trigger_exception: false

    front_left_wheel_command_joint_name: "velocity_left_1_joint"
    front_right_wheel_command_joint_name: "velocity_right_1_joint"
    rear_right_wheel_command_joint_name: "velocity_right_2_joint"
    rear_left_wheel_command_joint_name: "velocity_left_2_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      # based on urdf 
      wheel_radius: 0.0485
      # based on urdf , L=0.325/2=0.1625 meters, W=0.260/2=0.13 meters
      # The sum of robot center projection would be: L+W=0.1625+0.13=0.2925 meters
      # sum_of_robot_center_projection_on_X_Y_axis: 0.2925

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    #  Adjust these values based on the hardware's capabilities
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
