controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: velocity_left_1_joint
    front_right_wheel_command_joint_name: velocity_right_1_joint
    rear_right_wheel_command_joint_name: velocity_right_2_joint
    rear_left_wheel_command_joint_name: velocity_left_2_joint
    
    wheel_radius: 0.0485
    
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
