/**:
  ros__parameters:
    use_sim_time: false

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Controllers that are to be loaded
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters: {}

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "velocity_left_1_joint"
    front_right_wheel_command_joint_name: "velocity_right_1_joint"
    rear_left_wheel_command_joint_name: "velocity_left_2_joint"
    rear_right_wheel_command_joint_name: "velocity_right_2_joint"
    wheel_radius: 0.0485
    wheel_separation_width: 0.2676  # meters
    wheel_separation_length: 0.12   # meters
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    velocity_rolling_window_size: 10
