controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Declare the controllers that you want to run
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

# Simple flat parameters
controller_manager.ros__parameters.mecanum_drive_controller.front_left_wheel_command_joint_name: "velocity_left_1_joint"
controller_manager.ros__parameters.mecanum_drive_controller.front_right_wheel_command_joint_name: "velocity_right_1_joint"
controller_manager.ros__parameters.mecanum_drive_controller.rear_left_wheel_command_joint_name: "velocity_left_2_joint"
controller_manager.ros__parameters.mecanum_drive_controller.rear_right_wheel_command_joint_name: "velocity_right_2_joint"
controller_manager.ros__parameters.mecanum_drive_controller.wheel_radius: 0.0485
controller_manager.ros__parameters.mecanum_drive_controller.base_frame_id: "base_link"
controller_manager.ros__parameters.mecanum_drive_controller.odom_frame_id: "odom"
controller_manager.ros__parameters.mecanum_drive_controller.enable_odom_tf: true
